from helper.mailjet_helper import send_test_email

status, response = send_test_email(
    recipient="vishal080804@gmail.com",
    subject="Test Email from Gemini Integration",
    body="This is a test email generated by Gemini AI.",
    image_path="generated_image.png"
)
print(f"Mailjet status: {status}")
print(response)
